create table employee (
    id bigint generated by default as identity,
    admin boolean, first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null unique,
    version integer,
    supervisor bigint,
    primary key (id)
);
create table expense (
    id bigint generated by default as identity,
    ammount double not null check (ammount>=0),
    approved boolean,
    description varchar(255) not null,
    expense_date timestamp not null,
    version integer,
    reporter bigint,
    primary key (id)
);
alter table employee
    add constraint FK4722E6AE5853634D
    foreign key (supervisor)
    references employee;
alter table expense
    add constraint FKB1F4C858A408F4C6
    foreign key (reporter)
    references employee;